export const TMDB = {
  imageBaseUrl: 'https://image.tmdb.org/t/p/w500',
  imageSmallUrl: 'https://image.tmdb.org/t/p/w200',
  imageMiddleUrl: 'https://image.tmdb.org/t/p/w1280/',
  imageBigUrl: 'https://image.tmdb.org/t/p/w1920/',
  apiBaseMovie: 'https://api.themoviedb.org/3/movie/',
  apiBaseTV: 'https://api.themoviedb.org/3/tv/',
  apiUrlPerson: 'https://api.themoviedb.org/3/person/',
  urlPerson: 'https://api.themoviedb.org/3/person/popular?language=en-US&page=',
  urlPersonPage: 'https://api.themoviedb.org/3/person/popular?language=en-US&page=1',
  apiTrends: 'https://api.themoviedb.org/3/trending/movie/day?language=en-US',
  apiLanguage: '?language=en-US',
  apiReviews: '/reviews?language=en-US&page=1',
  apiCredits: '/credits?language=en-US',
  apiCombinedCredits: '/combined_credits',
  apiRecommend: '/recommendations',
};